# Generated by Django 4.1.3 on 2023-09-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_remove_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('news', 'Новость'), ('article', 'Статья')], default='new', max_length=20),
        ),
    ]
